CREATE DATABASE CONCESSIONARIA
GO


USE CONCESSIONARIA
GO

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL

)
GO

CREATE TABLE MODELO(
	IDMODELO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	ID_MARCA INT

)
GO


CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY IDENTITY,
	PRECO DECIMAL(10,2) NOT NULL,
	SITUACAO VARCHAR(20) DEFAULT 'DISPONIVEL',
	PLACA VARCHAR(10) UNIQUE,
	ANO INT NOT NULL,
	COR VARCHAR(15) NOT NULL,
	ID_MODELO INT,


)
GO

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	CPF VARCHAR(11) UNIQUE NOT NULL,
	SEXO CHAR(1) NOT NULL,
	CHECK (SEXO IN('F','M')),
	EMAIL VARCHAR(30) NOT NULL

)
GO

CREATE TABLE VENDEDOR(
	IDVENDEDOR INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	DATA_CONTRATACAO DATE

)
GO

CREATE TABLE FORMA_PAGAMENTO(
	IDPAGAMENTO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
)
GO


CREATE TABLE VENDAS(
	IDVENDA INT PRIMARY KEY IDENTITY,
	DATA_VENDA DATE NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	ID_CLIENTE INT,
	ID_VENDEDOR INT,
	ID_PAGAMENTO INT,
	ID_CARRO INT

)
GO


/* CONSTRAINTS */

ALTER TABLE MODELO
ADD CONSTRAINT FK_MODELO_MARCA
FOREIGN KEY (ID_MARCA) REFERENCES MARCA(IDMARCA)
GO

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MODELO
FOREIGN KEY (ID_MODELO) REFERENCES MODELO(IDMODELO)
GO


ALTER TABLE VENDAS 
ADD CONSTRAINT FK_VENDAS_PAGAMENTO
FOREIGN KEY (ID_PAGAMENTO) REFERENCES FORMA_PAGAMENTO(IDPAGAMENTO)
GO

ALTER TABLE VENDAS 
ADD CONSTRAINT FK_VENDAS_CLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
GO

ALTER TABLE VENDAS 
ADD CONSTRAINT FK_VENDAS_VENDEDOR
FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(IDVENDEDOR)
GO

ALTER TABLE VENDAS
ADD CONSTRAINT FK_VENDAS_CARRO
FOREIGN KEY (ID_CARRO) REFERENCES CARRO(IDCARRO)
GO

/* INSERINDO VALORES AS TABELAS */

INSERT INTO MARCA VALUES('TOYOTA'),
						('HONDA'),
						('VOLKSWAGEN'),
						('CHEVROLET'),
						('FORD'),
						('HYUNDAI'),
						('FIAT'),
						('JEEP'),
						('NISSAN'),
						('BMW')
GO

INSERT INTO MODELO(NOME,ID_MARCA) 
			VALUES('COROLLA',1),
				  ('COROLLA CROSS',1),
				  ('HILUX',1),
				  ('YARIS',1),
				  ('ETIOS',1)
GO

INSERT INTO MODELO(NOME,ID_MARCA) 
			VALUES('CIVIC',2),
				  ('CITY',2),
				  ('HR-V',2),
				  ('FIT',2),
				  ('CR-V',2)
GO

INSERT INTO MODELO(NOME,ID_MARCA) 
			VALUES('GOL',3),
				  ('POLO',3),
				  ('VIRTUS',3),
				  ('JETTA',3),
				  ('T-CROSS',3)
GO

INSERT INTO MODELO(NOME,ID_MARCA) 
			VALUES('ONIX',4),
				  ('ONIX PLUS',4),
				  ('CRUZE',4),
				  ('TRAKER',4),
				  ('S10',4)
GO

INSERT INTO MODELO(NOME,ID_MARCA) 
			VALUES('KA',5),
				  ('FIESTA',5),
				  ('ECOSPORT',5),
				  ('RANGER',5),
				  ('MAVERIK',5)
GO

INSERT INTO MODELO(NOME,ID_MARCA) 
			VALUES('HB20',6),
				  ('HB20S',6),
				  ('CRETA',6),
				  ('TUCSON',6),
				  ('SANTA FE',6)
GO

INSERT INTO MODELO(NOME,ID_MARCA) 
			VALUES('UNO',7),
				  ('ARGO',7),
				  ('CRONOS',7),
				  ('TORO',7),
				  ('STRADA',7)
GO

INSERT INTO MODELO(NOME,ID_MARCA) 
			VALUES('RENEGADE',8),
				  ('COMPASS',8),
				  ('COMMANDER',8)
GO

INSERT INTO MODELO(NOME,ID_MARCA) 
			VALUES('MARCH',9),
				  ('VERSA',9),
				  ('SENTRA',9),
				  ('KICKS',9),
				  ('FRONTIER',9)
GO

INSERT INTO MODELO(NOME,ID_MARCA) 
			VALUES('SERIE 1',10),
				  ('SERIE 3',10),
				  ('X1',10),
				  ('X3',10),
				  ('X5',10)
GO


INSERT INTO Carro (ID_MODELO, ANO, COR, PRECO,PLACA)
VALUES
 -- Toyota
 (1, 2022, 'Preto', 89900.00, 'ABC1D23'),   -- Corolla
 (2, 2023, 'Branco', 134900.00, 'DEF4G56'), -- Corolla Cross
 (3, 2021, 'Prata', 189900.00, 'GHI7J89'),  -- Hilux
 (4, 2020, 'Cinza', 75900.00, 'JKL0M12'),   -- Yaris
 (5, 2019, 'Vermelho', 68900.00, 'NOP3Q45')-- Etios

 GO

 INSERT INTO Carro (ID_MODELO, ANO, COR, PRECO, PLACA)
VALUES
 -- Honda
 (6, 2022, 'Preto', 112000.00, 'RST6U78'),  -- Civic
 (7, 2023, 'Azul', 87900.00, 'VWX9Y01'),    -- City
 (8, 2021, 'Branco', 119900.00, 'BCD2E34'), -- HR-V
 (9, 2020, 'Prata', 69900.00, 'FGH5I67'),   -- Fit
 (10, 2022, 'Cinza', 159900.00, 'IJK8L90') -- CR-V
 GO

 INSERT INTO Carro (ID_MODELO, ANO, COR, PRECO, PLACA)
VALUES
 -- Volkswagen
 (11, 2019, 'Branco', 55900.00, 'MNO1P23'), -- Gol
 (12, 2021, 'Preto', 78900.00, 'QRS4T56'),  -- Polo
 (13, 2023, 'Prata', 104900.00, 'UVW7X89'), -- Virtus
 (14, 2022, 'Cinza', 139900.00, 'YZA0B12'), -- Jetta
 (15, 2023, 'Azul', 129900.00, 'CDE3F45') -- T-Cross
 GO


 INSERT INTO Carro (ID_MODELO, ANO, COR, PRECO, PLACA)
VALUES
 -- Chevrolet
 (16, 2022, 'Branco', 74900.00, 'GHI6J78'), -- Onix
 (17, 2023, 'Preto', 82900.00, 'KLM9N01'),  -- Onix Plus
 (18, 2021, 'Prata', 109900.00, 'OPQ2R34'), -- Cruze
 (19, 2022, 'Cinza', 134900.00, 'STU5V67'), -- Tracker
 (20, 2020, 'Branco', 179900.00, 'WXY8Z90')-- S10
 GO



INSERT INTO CLIENTE (NOME, CPF,SEXO, EMAIL)
VALUES
 ('Carlos Henrique Silva', '12345678901','M','carlos.silva@email.com'),
 ('Mariana Souza', '23456789012','F','mariana.souza@email.com'),
 ('João Pedro Almeida', '34597890123','M','joao.almeida@email.com'),
 ('Fernanda Costa', '45678901234','F','fernanda.costa@email.com'),
 ('Rafael Pereira', '56798902345','M','rafael.pereira@email.com'),
 ('Lucas Martins', '67890123456','M','lucas.martins@email.com'),
 ('Ana Paula Ribeiro', '7890123456','F','ana.ribeiro@email.com'),
 ('Bruno Fernandes', '89072345678','M','bruno.fernandes@email.com'),
 ('Patrícia Lima', '90123456789','F','patricia.lima@email.com'),
 ('Diego Rocha', '01234567890','M','diego.rocha@email.com')
 GO

 INSERT INTO VENDEDOR(NOME, DATA_CONTRATACAO)
VALUES
 ('Marcos Oliveira', '2021-03-15'),
 ('Ana Beatriz Santos', '2022-07-10'),
 ('Ricardo Menezes', '2020-01-20'),
 ('Juliana Ferreira', '2023-02-05'),
 ('Paulo Henrique Costa', '2019-11-30')
 GO

 INSERT INTO VENDEDOR VALUES( 'LUIS FELIPE', '2023-07-21')
 GO

 INSERT INTO FORMA_PAGAMENTO VALUES('PIX'),
								   ('CARTAO'),
								   ('FINANCIAMENTO')

GO

INSERT INTO VENDAS
(DATA_VENDA, ID_CLIENTE, ID_VENDEDOR, ID_CARRO, ID_PAGAMENTO, VALOR)
VALUES
 ('2024-01-10', 1, 1, 2, 1, 78500.00),
 ('2024-01-15', 3, 2, 6, 2, 112000.00),
 ('2024-01-20', 5, 3, 11, 3, 55900.00),
 ('2024-02-01', 2, 1, 8, 1, 119900.00),
 ('2024-02-10', 4, 4, 14, 2, 139900.00)
 GO


/* QUERYS */

/* Liste todos os carros que estão com status 'Disponível', mostrando:
marca, modelo, ano e preco */

SELECT MA.NOME,
	   MO.NOME,
	   C.ANO,
	   C.PRECO
FROM CARRO C
INNER JOIN MODELO MO
ON C.ID_MODELO = MO.IDMODELO
INNER JOIN MARCA MA
ON MO.ID_MARCA = MA.IDMARCA
WHERE C.SITUACAO = 'DISPONIVEL'
GO

/* Mostre o nome de todos os clientes que já realizaram pelo menos uma compra. */

SELECT C.NOME 
FROM CLIENTE C
INNER JOIN VENDAS V
ON V.ID_CLIENTE = C.IDCLIENTE
GO

/* Liste todos os vendedores que ainda não realizaram nenhuma venda. */

SELECT IDVENDEDOR, V.NOME
FROM VENDEDOR V 
LEFT JOIN VENDAS VE
ON VE.ID_VENDEDOR = V.IDVENDEDOR
WHERE ID_VENDEDOR IS NULL
GO

/* Exiba o total de carros cadastrados por marca. */

SELECT M.NOME, COUNT(IDCARRO) AS 'QUANTIDADE'
FROM MARCA M
INNER JOIN MODELO MO
ON M.IDMARCA = MO.ID_MARCA
INNER JOIN CARRO C
ON MO.IDMODELO = C.ID_MODELO
GROUP BY(M.NOME)
GO

/* Mostre o valor total vendido por cada vendedor. */

SELECT V.NOME, SUM(VE.VALOR) AS 'VALOR TOTAL VENDIDO'
FROM VENDEDOR V
INNER JOIN VENDAS VE
ON V.IDVENDEDOR	= VE.ID_VENDEDOR
GROUP BY V.NOME
GO

/* Exiba a quantidade de carros vendidos por forma de pagamento.*/

SELECT FP.NOME,COUNT(C.IDCARRO) AS 'QUANTIDADE DE CARROS VENDIDOS'
FROM FORMA_PAGAMENTO FP
INNER JOIN VENDAS VE
ON FP.IDPAGAMENTO = VE.ID_PAGAMENTO
INNER JOIN CARRO C
ON VE.ID_CARRO = C.IDCARRO
GROUP BY FP.NOME
GO

/* Liste os clientes e o valor total gasto por cada um, ordenando do maior para o menor. */

SELECT C.NOME, SUM(V.VALOR) AS 'VALOR TOTAL'
FROM CLIENTE C
INNER JOIN VENDAS V
ON C.IDCLIENTE = V.ID_CLIENTE
GROUP BY C.NOME
ORDER BY [VALOR TOTAL] DESC
GO

/* Mostre o ticket médio de venda da concessionária. */

SELECT AVG(VALOR) AS 'TICKET MÉDIO'
FROM VENDAS
GO

/* Liste os carros que nunca foram vendidos. */

SELECT M.NOME 
FROM MODELO M
INNER JOIN CARRO C
ON M.IDMODELO = C.ID_MODELO
LEFT JOIN VENDAS V
ON C.IDCARRO = V.ID_CARRO
WHERE V.ID_CARRO IS NULL
GO


/* Mostre o vendedor que realizou a maior venda individual. */

SELECT TOP 1
    V.NOME AS Vendedor,
    VE.VALOR AS MaiorVenda
FROM VENDAS VE
INNER JOIN VENDEDOR V
    ON VE.ID_VENDEDOR = V.IDVENDEDOR
ORDER BY VE.VALOR DESC;

/* TRIGGER PARA ATUALIZAR STATUS DO CARRO APOS SER VENDIDO. */

CREATE TRIGGER TRG_ATUALIZA_SITUACAO_CARRO
ON VENDAS
AFTER INSERT 
AS
BEGIN
	UPDATE C
	SET C.SITUACAO = 'VENDIDO'
	FROM CARRO C
	INNER JOIN inserted I
		ON C.IDCARRO = I.ID_CARRO
	
	PRINT 'TRIGGER EXECUTADA COM SUCESSO'

END
GO


SELECT * FROM CARRO
GO

INSERT INTO VENDAS
(DATA_VENDA, ID_CLIENTE, ID_VENDEDOR, ID_CARRO, ID_PAGAMENTO, VALOR)
VALUES
 ('2022-05-10', 1, 3, 20, 1, 179900.00)
 GO

 SELECT * FROM VENDAS
 GO

 /* CRIAÇÃO DE BANCO SO PARA BACKUPS + TABELA BACKUP PARA VENDAS + TRIGGER PARA NÃO PERDER HISTORICO DE VENDAS */

CREATE DATABASE BACKUPS
GO

USE BACKUPS

 CREATE TABLE BACKUP_VENDAS(
	IDBACKUP INT PRIMARY KEY IDENTITY,
	DATA_VENDA DATE NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	ID_CLIENTE INT,
	ID_VENDEDOR INT,
	ID_PAGAMENTO INT,
	ID_CARRO INT,
	TIPO_OPERACAO VARCHAR(10) NOT NULL,
	DATA_OPERACAO DATETIME

 )
 GO

 DROP TABLE BACKUP_VENDAS

 CREATE TRIGGER TRG_BACKUP_VENDAS
 ON VENDAS
 AFTER INSERT,DELETE,UPDATE
 AS
 BEGIN
		INSERT INTO BACKUPS.dbo.BACKUP_VENDAS (DATA_VENDA,VALOR,ID_CLIENTE,ID_VENDEDOR,ID_PAGAMENTO,ID_CARRO,
										   TIPO_OPERACAO,DATA_OPERACAO)
		
		SELECT
			I.DATA_VENDA,
			I.VALOR,
			I.ID_CLIENTE,
			I.ID_VENDEDOR,
			I.ID_PAGAMENTO,
			I.ID_CARRO,
			'INSERT',
			GETDATE()
		FROM inserted I

		UNION ALL

		    -- DELETE
    SELECT 
        D.DATA_VENDA,
        D.VALOR,
        D.ID_CLIENTE,
        D.ID_VENDEDOR,
        D.ID_PAGAMENTO,
        D.ID_CARRO,
        'DELETE',
        GETDATE()
    FROM deleted D
END
GO

SELECT *
FROM VENDAS
WHERE IDVENDA = 5
GO

DELETE FROM VENDAS
WHERE IDVENDA = 5
GO

select * from BACKUP_VENDAS
Go

/* PROCEDURE DE FECHAMENTO DE VENDAS */

SELECT * FROM VENDAS
GO

CREATE PROC FECHAMENTO_VENDAS @DATA_VENDA DATE, @VALOR DECIMAL(10,2), @ID_CLIENTE INT,
							  @ID_VENDEDOR INT, @ID_PAGAMENTO INT, @ID_CARRO INT
AS
BEGIN
		SET NOCOUNT ON;

		IF EXISTS( SELECT 1 
			       FROM CARRO
				   WHERE IDCARRO = @ID_CARRO
				   AND SITUACAO = 'VENDIDO')
BEGIN
	RAISERROR('Este carro ja foi vendido',16,1);
	RETURN;
	END

	DECLARE @ID_NOVA_VENDA INT

	INSERT INTO VENDAS(DATA_VENDA,VALOR,ID_CLIENTE,ID_VENDEDOR,ID_PAGAMENTO, ID_CARRO)
				VALUES(@DATA_VENDA,@VALOR,@ID_CLIENTE, @ID_VENDEDOR, @ID_PAGAMENTO, @ID_CARRO)

	SET @ID_NOVA_VENDA = SCOPE_IDENTITY();

	UPDATE CARRO 
	SET SITUACAO = 'VENDIDO'
	WHERE IDCARRO = @ID_CARRO

	SELECT @ID_NOVA_VENDA AS ID_NOVA_VENDA;

END
GO

EXEC FECHAMENTO_VENDAS '2026/02/06',129900.00,3,5,2,15

SELECT * FROM CARRO;

SELECT * FROM VENDAS










				