CREATE PROC FECHAMENTO_VENDAS @DATA_VENDA DATE, @VALOR DECIMAL(10,2), @ID_CLIENTE INT,
							  @ID_VENDEDOR INT, @ID_PAGAMENTO INT, @ID_CARRO INT
AS
BEGIN
		SET NOCOUNT ON;

		IF EXISTS( SELECT 1 
			       FROM CARRO
				   WHERE IDCARRO = @ID_CARRO
				   AND SITUACAO = 'VENDIDO')
BEGIN
	RAISERROR('Este carro ja foi vendido',16,1);
	RETURN;
	END

	DECLARE @ID_NOVA_VENDA INT

	INSERT INTO VENDAS(DATA_VENDA,VALOR,ID_CLIENTE,ID_VENDEDOR,ID_PAGAMENTO, ID_CARRO)
				VALUES(@DATA_VENDA,@VALOR,@ID_CLIENTE, @ID_VENDEDOR, @ID_PAGAMENTO, @ID_CARRO)

	SET @ID_NOVA_VENDA = SCOPE_IDENTITY();

	UPDATE CARRO 
	SET SITUACAO = 'VENDIDO'
	WHERE IDCARRO = @ID_CARRO

	SELECT @ID_NOVA_VENDA AS ID_NOVA_VENDA;

END
GO
