
CREATE DATABASE BACKUPS
GO

USE BACKUPS

 CREATE TABLE BACKUP_VENDAS(
	IDBACKUP INT PRIMARY KEY IDENTITY,
	DATA_VENDA DATE NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	ID_CLIENTE INT,
	ID_VENDEDOR INT,
	ID_PAGAMENTO INT,
	ID_CARRO INT,
	TIPO_OPERACAO VARCHAR(10) NOT NULL,
	DATA_OPERACAO DATETIME

 )
 GO
 
