
 CREATE TRIGGER TRG_BACKUP_VENDAS
 ON VENDAS
 AFTER INSERT,DELETE,UPDATE
 AS
 BEGIN
		INSERT INTO BACKUPS.dbo.BACKUP_VENDAS (DATA_VENDA,VALOR,ID_CLIENTE,ID_VENDEDOR,ID_PAGAMENTO,ID_CARRO,
										   TIPO_OPERACAO,DATA_OPERACAO)
		
		SELECT
			I.DATA_VENDA,
			I.VALOR,
			I.ID_CLIENTE,
			I.ID_VENDEDOR,
			I.ID_PAGAMENTO,
			I.ID_CARRO,
			'INSERT',
			GETDATE()
		FROM inserted I

		UNION ALL

		    -- DELETE
    SELECT 
        D.DATA_VENDA,
        D.VALOR,
        D.ID_CLIENTE,
        D.ID_VENDEDOR,
        D.ID_PAGAMENTO,
        D.ID_CARRO,
        'DELETE',
        GETDATE()
    FROM deleted D
END
GO
