CREATE TRIGGER TRG_ATUALIZA_SITUACAO_CARRO
ON VENDAS
AFTER INSERT 
AS
BEGIN
	UPDATE C
	SET C.SITUACAO = 'VENDIDO'
	FROM CARRO C
	INNER JOIN inserted I
		ON C.IDCARRO = I.ID_CARRO
	
	PRINT 'TRIGGER EXECUTADA COM SUCESSO'

END
GO
